server:
  port: 8081

spring:
  application:
    name: order-service
  
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
      retry-backoff-ms: 1000
      batch-size: 16384
      buffer-memory: 33554432
      compression-type: snappy
      properties:
        enable.idempotence: true
        max.in.flight.requests.per.connection: 5
        delivery.timeout.ms: 120000
    properties:
      spring.json.add.type.headers: false

logging:
  level:
    com.flashstream: DEBUG
    org.apache.kafka: INFO
